### ISSUE TITLE
no data in corrected-group

### ISSUE THREAD

**Issue by sathishkumarRamaswamy** [marcus1487/nanoraw#36]
Dear Team,
I am running following commands, I didnt get any error/warnning message, but i am not getting corrected group data.

nanoraw genome_resquiggle \$g1Dir $genomeFn --bwa-mem-executable ./bwa \ --normalization-type median \ --corrected-group RawGenomeCorrected_bwamem_000 --overwrite \      --failed-reads-filename testing.group1.bwamem.failed_read.txt \
      --2d --processes 4

**Comment by marcus1487** [comment]
Hi, Happy to help. 

What was the output to stderr and/or the `--failed-read-filename`? As a first guess, have you double checked that `$g1Dir` contains the FAST5 files (e.g. `ls $g1Dir | less` should give you a long list of FAST5 files)? 

If the FAST5 files are in a subdirectory (or group of subdirectory, using the newest version of Metrichor I believe does this), nanoraw cannot find them without specific instruction as to where to look. I have not had a chance to put up instructions for this, but you should be able to use the `--fast5-pattern` with a pattern in double quotes specifying the location of all FAST5 files. If this is the case then you should have output that indicates that very few files were to be processed (i.e. `Correcting 0 files with 1 subgroup(s)/read(s) each (Will print a dot for each 100 files completed).`).

Hopefully this might be helpful, but if there is another issue, maybe some more detail might help to identify the issue. Thanks!

**Comment by marcus1487** [comment]
Without more information I am closing this issue. Provide more info if this issue persists.

**Comment by smm19900210** [comment]
hi marcus1487, i met the same problem, but i got corrected group, but it empty. what should i do?
