### ISSUE TITLE
plot error

### ISSUE THREAD

**Issue by athulmenon** [marcus1487/nanoraw#37]
I have installed rpy2, R and R package ggplot2 but still its showing following error

nanoraw plot_max_coverage --fast5-basedirs fast5/ --2d --num-bases 21 --overplot-threshold 1000
************************************************************
ERROR: Must have rpy2, R and R package ggplot2 installed in order to plot.

**Comment by marcus1487** [comment]
I had this issue on one of my servers as well. In my case it was a bad rpy2 installation (specifically the `rpy2.robjects` module). Something about an undefined symbol in one of the libreadline dependency for me. Try running `python -c "import rpy2.robjects; from rpy2.robjects.packages import importr; importr('ggplot2');"` may point you to the root of the error. I may add this bit of code to the error message in the future to help users debug. My workaround was a virtual environment with a fresh install of ryp2. Hope this helps!

**Comment by marcus1487** [comment]
I have added this instruction to the error message to check rpy2 install issues in commit 710310094d2774e295ae37345f688253a12eefbe . So users will be able to check install issues immediately.
