### ISSUE TITLE
Start_time not present in fast5

### ISSUE THREAD

**Issue by usamec** [marcus1487/nanoraw#39]
I am using fast5 files from here http://lab.loman.net/2017/03/09/ultrareads-for-nanopore/?rev1 and I get following output:

> Failed reads summary:
>         'start_time' :  42
>         No events or corrupted events in file. Likely a segmentation error or mis-specified basecall-subgroups (--2d?). :       6

I believe the second error is normal (failed based call). The first error is related to missing start_time attribute in event data and raw data.
Can this be fixed somehow? Like setting it to zero?

**Comment by marcus1487** [comment]
I have seen this in personal communications with another user, but have yet to find the root of the problem. nanoraw does need the start_time attribute from the fast5 to anchor the events data to the raw data. Without a correct anchoring nanoraw cannot correctly link the event and raw data and thus cannot proceed.

One possibility I did find is that these are from mux scan files. If you save the failed-reads-filename this may point to the issue. 

Are you getting some corrected reads, or are all of your reads failing by one of these two reasons?

**Comment by usamec** [comment]
All files are failing. I think, that we can infer start_time by aligning raw event to called events.
I will try at some point and let you know.

**Comment by marcus1487** [comment]
I pushed a fix yesterday. If you update to the most recent github you should not see this error anymore.

**Comment by usamec** [comment]
Works now, thanks.
