### ISSUE TITLE
explanation of genome_alignment, read_alignment, read_segments and Events

### ISSUE THREAD

**Issue by liuqianhn** [marcus1487/nanoraw#44]
Hi Marcus, 

Could you please explain more about "/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment/genome_alignment Dataset {419}"
"/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment/read_alignment Dataset {419}"
"/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment/read_segments Dataset {369}"
"/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events Dataset {417}"? 

I understand that `read_alignment` should be paired with `read_segments`, and `genome_alignment` should be paired with `Events` here (Please correct me if I am wrong). But how to calculate the values in Events here? Which one is used in the plot? Thanks.

**Comment by marcus1487** [comment]
Have you taken a look at the docs: https://nanoraw.readthedocs.io/en/latest/resquiggle.html#nanoraw-fast5-format

Not sure to which plot you are referring. There are many plotting functions as part of nanoraw.

**Comment by liuqianhn** [comment]
Hi Marcus, Thank you for your quick reply. I will read the document. Thanks. 

If I used `nanoraw plot_most_significant`, which signals were used, those in `Events` or calculated according to `read_segments`?

**Comment by marcus1487** [comment]
The position of signal used is taken from `Events` data table. The actual raw signal is found in the `Raw` group. Everything under the `Alignment` group is used only for plotting the correction process (`plot_correction` and `plot_multi_correction`).
