### ISSUE TITLE
Suggest minimap2 as option

### ISSUE THREAD

**Issue by timp0** [marcus1487/nanoraw#46]
Minimap2 is a huge improvement (IMO) at least in speed over bwa mem or graphmap - I suggest adding it as an option, or at least allowing bam input instead of specifying aligner

**Comment by marcus1487** [comment]
I agree that this would be a great option. Adding a mapper should not be that hard, but I don't have a ton of time for support right now. I would be happy to merge a pull request though... Here is the point at which the mapper would be inserted: https://github.com/marcus1487/nanoraw/blob/eea4af8fcaf5c2e3b0a7bbbba89e9a25f4f91e68/nanoraw/resquiggle.py#L704

As for the BAM input option, that is not feasible in the nanoraw framework as the sequence must be linked throughout to the raw signal. I'm not sure there is a concise (or even possible) way to do that in BAM format.

**Comment by omegahh** [comment]
Actually, you rewrite nanoraw in the repo: [nanoporetech/tombo](https://github.com/nanoporetech/tombo)

tombo uses minimap2, isn't it? 

Does that mean this repo is closed? If that's true, please tell people the new repo in README. No offense, I spent almost two days in reading every line of codes in this repo, but finally find a new and executable repo in [nanoporetech/tombo](https://github.com/nanoporetech/tombo)
