### ISSUE TITLE
mapping raw or normalized signal without called events

### ISSUE THREAD

**Issue by al2na** [marcus1487/nanoraw#48]
Sorry for opening an issue for a question. Is it possible to map the signal to the genome for fast5 files that doesn't have the event calls. New basecalling doesn't depend on events anymore and I'm not sure if the basecaller provides event calls anymore. Thanks for the very useful package!!

**Comment by marcus1487** [comment]
At this time there is not a way to run nanoraw without called events. The events from albacore now do make this problematic as they are not associated with the breakpoints between bases, though the nanoraw algorithm does still work. The breakpoints between bases will just be off by a bit.
