### ISSUE TITLE
Resquiggle fails with `Events appear to start before the raw signal` for direct RNA seq

### ISSUE THREAD

**Issue by lpryszcz** [marcus1487/nanoraw#52]
HI, I wanted to resquiggle direct RNA seq data from [NA12878](https://github.com/nanopore-wgs-consortium/NA12878), but it's failing with `Events appear to start before the raw signal`. Do you plan to support direct RNA seq data anytime soon?

**Comment by marcus1487** [comment]
Hi, nanoraw is no longer being maintained and was not specifically designed to deal with RNA reads, given their 3' to 5' sequencing direction. The derivative work Tombo (https://github.com/nanoporetech/tombo) is the recommended tool for this approach now and supports RNA reads as well. I intend to put a deprecation notice and pointer to Tombo in the README here soon.

**Comment by lpryszcz** [comment]
Thanks!
